FROM vimagick/dante
RUN useradd denis \
    && echo 'denis:123qwe' | chpasswd \
    && useradd anton \
    && echo 'anton:12345' | chpasswd \
    && useradd alex \
    && echo 'alex:2018as1' | chpasswd
